/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.FornecedoresDao;
import br.com.projeto.dao.ProdutosDao;
import br.com.projeto.model.Fornecedores;
import br.com.projeto.model.Produtos;
import br.com.projeto.model.Utilitarios;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduarda
 */
public class JFrmProdutos extends javax.swing.JFrame {

    /**
     * Creates new form JFrmCliente
     */
    public JFrmProdutos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jPDadosProdutos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomePro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        For = new javax.swing.JComboBox<>();
        LimparProduto = new javax.swing.JButton();
        EditarProduto = new javax.swing.JButton();
        ExcluirProduto = new javax.swing.JButton();
        SalvarProduto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtdesc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPDadosPessois = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNomeFor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        FtxtCep = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ftxtRg = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        ftxtCpf = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        ftxtCelular = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        cbAC = new javax.swing.JComboBox<>();
        fintNum = new javax.swing.JTextField();
        btLimparFornecedor = new javax.swing.JButton();
        btSalvarFornecedor = new javax.swing.JButton();
        btEditarFornecedor = new javax.swing.JButton();
        btExcluirFornecedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        btNovo = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Lohit Devanagari", 3, 24)); // NOI18N
        jLabel1.setText("Mercado Duda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane8.setBackground(new java.awt.Color(153, 153, 255));
        jTabbedPane8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPDadosProdutos.setBackground(new java.awt.Color(244, 243, 243));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Código:");

        txtId.setEditable(false);
        txtId.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Nome:");

        txtNomePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Preço:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("Qtd. Estoque:");

        txtQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel13.setText("Fornecedor:");

        For.setBackground(new java.awt.Color(204, 204, 204));
        For.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        For.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        For.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForActionPerformed(evt);
            }
        });

        LimparProduto.setBackground(new java.awt.Color(204, 204, 204));
        LimparProduto.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        LimparProduto.setText("Limpar");
        LimparProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LimparProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparProdutoActionPerformed(evt);
            }
        });

        EditarProduto.setBackground(new java.awt.Color(204, 204, 204));
        EditarProduto.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        EditarProduto.setText("Editar");
        EditarProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarProdutoActionPerformed(evt);
            }
        });

        ExcluirProduto.setBackground(new java.awt.Color(204, 204, 204));
        ExcluirProduto.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        ExcluirProduto.setText("Excluir");
        ExcluirProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirProdutoActionPerformed(evt);
            }
        });

        SalvarProduto.setBackground(new java.awt.Color(204, 204, 204));
        SalvarProduto.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        SalvarProduto.setText("Salvar");
        SalvarProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarProdutoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Descrição:");

        jTable.setBackground(new java.awt.Color(153, 153, 255));
        jTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jTable.setForeground(new java.awt.Color(51, 51, 51));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Descrição", "Preço", "Qtd.Estoque", "Fornecedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable.setGridColor(new java.awt.Color(204, 204, 204));
        jTable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPDadosProdutosLayout = new javax.swing.GroupLayout(jPDadosProdutos);
        jPDadosProdutos.setLayout(jPDadosProdutosLayout);
        jPDadosProdutosLayout.setHorizontalGroup(
            jPDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDadosProdutosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomePro, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(335, Short.MAX_VALUE))
                    .addGroup(jPDadosProdutosLayout.createSequentialGroup()
                        .addGroup(jPDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDadosProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPDadosProdutosLayout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(LimparProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(SalvarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(EditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPDadosProdutosLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtd)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(For, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
            .addGroup(jPDadosProdutosLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPDadosProdutosLayout.setVerticalGroup(
            jPDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosProdutosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtQtd)
                    .addComponent(jLabel13)
                    .addComponent(For, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPDadosProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimparProduto)
                    .addComponent(SalvarProduto)
                    .addComponent(EditarProduto)
                    .addComponent(ExcluirProduto))
                .addGap(29, 29, 29))
        );

        jTabbedPane8.addTab("Produtos", jPDadosProdutos);

        jPanel3.setBackground(new java.awt.Color(244, 243, 243));

        jPDadosPessois.setBackground(new java.awt.Color(244, 243, 243));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Código:");

        txtId1.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Nome:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setText("E-mail:");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel10.setText("CEP:");

        try {
            FtxtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel11.setText("Bairro:");

        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel12.setText("Endereço:");

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel14.setText("N°:");

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel15.setText("Cidade:");

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel16.setText("RG:");

        try {
            ftxtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel17.setText("CPF:");

        try {
            ftxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel18.setText("Celular:");

        try {
            ftxtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(## ) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel19.setText("UF:");

        cbAC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        fintNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fintNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPDadosPessoisLayout = new javax.swing.GroupLayout(jPDadosPessois);
        jPDadosPessois.setLayout(jPDadosPessoisLayout);
        jPDadosPessoisLayout.setHorizontalGroup(
            jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosPessoisLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDadosPessoisLayout.createSequentialGroup()
                        .addGroup(jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDadosPessoisLayout.createSequentialGroup()
                                .addGroup(jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPDadosPessoisLayout.createSequentialGroup()
                                        .addComponent(ftxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17))
                                    .addGroup(jPDadosPessoisLayout.createSequentialGroup()
                                        .addComponent(FtxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPDadosPessoisLayout.createSequentialGroup()
                                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fintNum, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPDadosPessoisLayout.createSequentialGroup()
                                        .addComponent(ftxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbAC, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPDadosPessoisLayout.createSequentialGroup()
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDadosPessoisLayout.createSequentialGroup()
                        .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeFor, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
        );
        jPDadosPessoisLayout.setVerticalGroup(
            jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosPessoisLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDadosPessoisLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNomeFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(ftxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FtxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBairro)
                    .addComponent(jLabel14)
                    .addComponent(fintNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDadosPessoisLayout.createSequentialGroup()
                        .addGroup(jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ftxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(ftxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(cbAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(205, 205, 205))
                    .addGroup(jPDadosPessoisLayout.createSequentialGroup()
                        .addGroup(jPDadosPessoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btLimparFornecedor.setBackground(new java.awt.Color(204, 204, 204));
        btLimparFornecedor.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btLimparFornecedor.setText("Limpar");
        btLimparFornecedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btLimparFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparFornecedorActionPerformed(evt);
            }
        });

        btSalvarFornecedor.setBackground(new java.awt.Color(204, 204, 204));
        btSalvarFornecedor.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btSalvarFornecedor.setText("Salvar");
        btSalvarFornecedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btSalvarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarFornecedorActionPerformed(evt);
            }
        });

        btEditarFornecedor.setBackground(new java.awt.Color(204, 204, 204));
        btEditarFornecedor.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btEditarFornecedor.setText("Editar");
        btEditarFornecedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btEditarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarFornecedorActionPerformed(evt);
            }
        });

        btExcluirFornecedor.setBackground(new java.awt.Color(204, 204, 204));
        btExcluirFornecedor.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btExcluirFornecedor.setText("Excluir");
        btExcluirFornecedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btExcluirFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirFornecedorActionPerformed(evt);
            }
        });

        jtable.setBackground(new java.awt.Color(153, 153, 255));
        jtable.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jtable.setForeground(new java.awt.Color(51, 51, 51));
        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "RG", "CPF", "E-mail", "Celular", "Cep", "Endereço", "N°", "Bairro", "Cidade", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtable.setGridColor(new java.awt.Color(204, 204, 204));
        jtable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btLimparFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btEditarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluirFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPDadosPessois, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPDadosPessois, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparFornecedor)
                    .addComponent(btSalvarFornecedor)
                    .addComponent(btEditarFornecedor)
                    .addComponent(btExcluirFornecedor))
                .addGap(15, 15, 15))
        );

        jTabbedPane8.addTab("Fornecedores", jPanel3);

        btNovo.setBackground(new java.awt.Color(102, 102, 102));
        btNovo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btNovo.setText("+ Novo");
        btNovo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btEditar.setBackground(new java.awt.Color(102, 102, 102));
        btEditar.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btEditar.setText("Editar");
        btEditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane8)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(401, 401, 401)
                    .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(356, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(405, 405, 405)
                    .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(359, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane8)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(313, 313, 313)
                    .addComponent(btNovo)
                    .addContainerGap(393, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(313, 313, 313)
                    .addComponent(btEditar)
                    .addContainerGap(393, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdActionPerformed
 
    private void ForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ForActionPerformed

    private void txtNomeProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProActionPerformed
     
    public void listarFornecedores() {
        
        DefaultTableModel modelo = (DefaultTableModel) jtable.getModel();
        modelo.setNumRows(0);
        FornecedoresDao dao = new FornecedoresDao();

        for (Fornecedores p : dao.listarFornecedores()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getRg(),
                p.getCpf(),
                p.getEmail(),
                p.getCelular(),
                p.getCep(),
                p.getEndereco(),
                p.getNumero(),
                p.getBairro(),
                p.getCidade(),
                p.getUf()
                
            });

        }

    }
    public void listarProduto() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();
        modelo.setNumRows(0);
         ProdutosDao dao = new ProdutosDao();
        
        for(Produtos p: dao.listarProdutos()){
            modelo.addRow(new Object[]{
                p.getCódigo(),
                p.getNome(),
                p.getDescricao(),
                p.getPreco(),
                p.getQtd_estoque(),
                p.getFornecedorId()
               
                
            
            });
        }
     }
     
     public void ProCombobox(){
         FornecedoresDao dao = new FornecedoresDao();
        
        for(Fornecedores p: dao.listarFornecedores()){
            For.removeItem(p.toString());
            For.addItem(p.toString());
            //For.removeItem(p.toString());
           //For.removeAllItems();
        }
     
     }
    private void SalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarProdutoActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        Produtos pro = new Produtos();
        
       pro.setNome(txtNomePro.getText());
        pro.setDescricao(txtdesc.getText());
        pro.setPreco(Double.parseDouble(txtPreco.getText()));
        pro.setQtd_estoque(txtQtd.getText());
        String t = For.getSelectedItem().toString();
        System.out.println(t.substring(0,1));
        pro.setFornecedorId(Integer.parseInt(t.substring(0,1)));
        
        
        ProdutosDao dao = new ProdutosDao();
        dao.cadastrarProduto(pro);
        new Utilitarios().limpaTela(jPDadosProdutos);
    }//GEN-LAST:event_SalvarProdutoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here
        listarProduto();
        ProCombobox();
        listarFornecedores();
        
        

    }//GEN-LAST:event_formWindowActivated

    private void LimparProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparProdutoActionPerformed
        // TODO add your handling code here:
        new Utilitarios().limpaTela(jPDadosProdutos);
    }//GEN-LAST:event_LimparProdutoActionPerformed

    private void EditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarProdutoActionPerformed
        // TODO add your handling code here:
        Produtos pro = new Produtos();
        
       pro.setNome(txtNomePro.getText());
        pro.setDescricao(txtdesc.getText());
        pro.setPreco(Double.parseDouble(txtPreco.getText()));
        pro.setQtd_estoque(txtQtd.getText());
        String t = For.getSelectedItem().toString();
        System.out.println(t.substring(0,1));
        pro.setFornecedorId(Integer.parseInt(t.substring(0,1)));
        pro.setCódigo(Integer.parseInt(txtId.getText()));
        
        ProdutosDao dao = new ProdutosDao();
        dao.alterarProduto(pro);
        new Utilitarios().limpaTela(jPDadosProdutos);
        
    }//GEN-LAST:event_EditarProdutoActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        jTabbedPane8.setSelectedIndex(0);
        txtId.setText(jTable.getValueAt(jTable.getSelectedRow(),0).toString());
        txtNomePro.setText(jTable.getValueAt(jTable.getSelectedRow(),1).toString());
        txtdesc.setText(jTable.getValueAt(jTable.getSelectedRow(),2).toString());
        txtPreco.setText(jTable.getValueAt(jTable.getSelectedRow(),3).toString());
        txtQtd.setText(jTable.getValueAt(jTable.getSelectedRow(),4).toString());
        For.setSelectedItem(jTable.getValueAt(jTable.getSelectedRow(),5) + getName());
        
        //cbAC.setSelectedItem(jtable.getValueAt(jtable.getSelectedRow(),11).toString());
    }//GEN-LAST:event_jTableMouseClicked

    private void ExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirProdutoActionPerformed
        // TODO add your handling code here:
        Produtos pro = new Produtos();
        pro.setCódigo(Integer.parseInt(txtId.getText()));
        ProdutosDao dao = new ProdutosDao();
        dao.excluirCliente(pro);
        new Utilitarios().limpaTela(jPDadosProdutos);
        
        
        
    }//GEN-LAST:event_ExcluirProdutoActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        new Utilitarios().limpaTela(jPDadosPessois);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btLimparFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparFornecedorActionPerformed
        // TODO add your handling code here:
        new Utilitarios().limpaTela(jPDadosPessois);
    }//GEN-LAST:event_btLimparFornecedorActionPerformed

    private void btSalvarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarFornecedorActionPerformed

        Fornecedores cli = new Fornecedores();
        cli.setNome(txtNomeFor.getText());
        cli.setRg(ftxtRg.getText());
        cli.setEmail(txtEmail.getText());
        cli.setCep(FtxtCep.getText());
        cli.setBairro(txtBairro.getText());

        cli.setCelular(ftxtCelular.getText());
        cli.setEndereco(txtEndereco.getText());
        cli.setCidade(txtCidade.getText());
        cli.setCpf(ftxtCpf.getText());
        cli.setNumero(Integer.parseInt(fintNum.getText()));
        cli.setUf(cbAC.getSelectedItem().toString());

        FornecedoresDao dao = new FornecedoresDao();
        dao.cadastrarFornecedores(cli);
       new Utilitarios().limpaTela(jPDadosPessois);

        //listar()

    }//GEN-LAST:event_btSalvarFornecedorActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        Fornecedores cli = new Fornecedores();

        cli.setNome(txtNomePro.getText());
        cli.setRg(ftxtRg.getText());
        cli.setEmail(txtEmail.getText());
        cli.setCep(FtxtCep.getText());
        cli.setBairro(txtBairro.getText());

        cli.setCelular(ftxtCelular.getText());
        cli.setEndereco(txtEndereco.getText());
        cli.setCidade(txtCidade.getText());
        cli.setCpf(ftxtCpf.getText());
        cli.setNumero(Integer.parseInt(fintNum.getText()));
        cli.setUf(cbAC.getSelectedItem().toString());

        cli.setId(Integer.parseInt(txtId.getText()));

        FornecedoresDao dao = new FornecedoresDao();
        dao.alterarFornecedores(cli);


    }//GEN-LAST:event_btEditarActionPerformed

    private void btEditarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarFornecedorActionPerformed
        // TODO add your handling code here:
        Fornecedores cli = new Fornecedores();

        cli.setNome(txtNomeFor.getText());
        cli.setRg(ftxtRg.getText());
        cli.setEmail(txtEmail.getText());
        cli.setCep(FtxtCep.getText());
        cli.setBairro(txtBairro.getText());

        cli.setCelular(ftxtCelular.getText());
        cli.setEndereco(txtEndereco.getText());
        cli.setCidade(txtCidade.getText());
        cli.setCpf(ftxtCpf.getText());
        cli.setNumero(Integer.parseInt(fintNum.getText()));
        cli.setUf(cbAC.getSelectedItem().toString());

        cli.setId(Integer.parseInt(txtId1.getText()));

        FornecedoresDao dao = new FornecedoresDao();
        dao.alterarFornecedores(cli);
        new Utilitarios().limpaTela(jPDadosPessois);

        

    }//GEN-LAST:event_btEditarFornecedorActionPerformed

    private void btExcluirFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirFornecedorActionPerformed

        // TODO add your handling code here:
        Fornecedores cli = new Fornecedores();
        cli.setId(Integer.parseInt(txtId1.getText()));

        FornecedoresDao dao = new FornecedoresDao();
        dao.excluirFornecedores(cli);
        new Utilitarios().limpaTela(jPDadosPessois);

    }//GEN-LAST:event_btExcluirFornecedorActionPerformed

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
        // TODO add your handling code here:
        //jTabbedPane8.setSelectedIndex(0);
        txtId1.setText(jtable.getValueAt(jtable.getSelectedRow(),0).toString());
        txtNomeFor.setText(jtable.getValueAt(jtable.getSelectedRow(),1).toString());
        ftxtRg.setText(jtable.getValueAt(jtable.getSelectedRow(),2).toString());
        ftxtCpf.setText(jtable.getValueAt(jtable.getSelectedRow(),3).toString());
        txtEmail.setText(jtable.getValueAt(jtable.getSelectedRow(),4).toString());
        ftxtCelular.setText(jtable.getValueAt(jtable.getSelectedRow(),5).toString());
        FtxtCep.setText(jtable.getValueAt(jtable.getSelectedRow(),6).toString());
        txtEndereco.setText(jtable.getValueAt(jtable.getSelectedRow(),7).toString());
        fintNum.setText(jtable.getValueAt(jtable.getSelectedRow(),8).toString());
        txtBairro.setText(jtable.getValueAt(jtable.getSelectedRow(),9).toString());
        txtCidade.setText(jtable.getValueAt(jtable.getSelectedRow(),10).toString());
        cbAC.setSelectedItem(jtable.getValueAt(jtable.getSelectedRow(),11).toString());

    }//GEN-LAST:event_jtableMouseClicked

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void fintNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fintNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fintNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarProduto;
    private javax.swing.JButton ExcluirProduto;
    private javax.swing.JComboBox<String> For;
    private javax.swing.JFormattedTextField FtxtCep;
    private javax.swing.JButton LimparProduto;
    private javax.swing.JButton SalvarProduto;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEditarFornecedor;
    private javax.swing.JButton btExcluirFornecedor;
    private javax.swing.JButton btLimparFornecedor;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvarFornecedor;
    private javax.swing.JComboBox<String> cbAC;
    private javax.swing.JTextField fintNum;
    private javax.swing.JFormattedTextField ftxtCelular;
    private javax.swing.JFormattedTextField ftxtCpf;
    private javax.swing.JFormattedTextField ftxtRg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPDadosPessois;
    private javax.swing.JPanel jPDadosProdutos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jtable;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtNomeFor;
    private javax.swing.JTextField txtNomePro;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtdesc;
    // End of variables declaration//GEN-END:variables
}
